lighthining_model :
  name : "MRSClassfication2D"
  parmas :
    model_name : "efficientnet_b7"
    model_params :
      cls_num_classes : 2

    learning_rate : 0.0001
    weight_decay : 0.0005
    T_0 : 100
    T_mult : 1
    eta_max : 0.001
    T_up : 20
    gamma : 0.5
    
datamodule :
  name : "BrainDataModule"
  dataset :
    name : 'MRSDataset2D'

  data_load_params :
    train_path : "/home/lab/inseo/brain/data/total2/train.csv"
    val_path : "/home/lab/inseo/brain/data/total2/val.csv"
    test_path : "/home/lab/inseo/brain/data/total2/test.csv"

  data_dir : "/home/lab/inseo/brain/data/total2"
  batch_size : 32
  num_workers : 7 
  pin_memory : False

trainer :
  precision : 16
  max_epochs : 100
  gradient_clip_val : 10
