lighthining_model :
  name : "MRSClassficationMultiModal"
  parmas :

  model :
    name : "Mc3D18MultiModalFeatureConcat"
    params :
      num_classes : 2
      clinical_feature_len : 11
      head : mlp 
      
  optimizer :
    name : "AdamW"
    params : 
      lr : 0.0001
      weight_decay : 0.0005
  
  scheduler :
    name : "CosineAnnealingWarmUpRestarts"
    params : 
      T_0 : 50
      T_mult : 1
      eta_max : 0.001
      T_up : 10
      gamma : 0.5

datamodule :
  name : "BrainDataModule"
  params : 

  dataset :
    name : 'MRSMultiDataset'
    params : 
      data_dir : "D:/study_d/project/brain/code/data/image"
  
  data_load_params :
    train_path : "D:/study_d/project/brain/code/data/annotation/train.csv"
    val_path : "D:/study_d/project/brain/code/data/annotation/val.csv"
    test_path : "D:/study_d/project/brain/code/data/annotation/test.csv"
    scaler_name : 'RobustScaler'
    categorical_cols : ['sex']
    numerical_cols : ['age','bmi','ini_nih','pre_mrs','hx_str','hx_htn','hx_smoke','hx_af','tx_throm']
    ignore_cols : ['image','label','mask_path'] 

  dataloader : 
    name :
    params :
      batch_size : 16
      num_workers : 0
      pin_memory : False

  transforms:
    train:
      LoadImaged : 
        keys : "img"
      AddChanneld :
        keys : "img"

      Spacingd : 
        keys : "img"
        pixdim : [1,1,5]

      Orientationd :
        keys : "img"
        axcodes : 'SPL'

      ScaleIntensityd :
        keys : "img"

      Resized :
        keys : "img"
        spatial_size : [48,256,256]

      RandRotated : 
        keys : "img"
        range_x : 0.2617993877991494

      EnsureTyped :
        keys : "img"

    val:
      LoadImaged : 
        keys : "img"

      AddChanneld :
        keys : "img"

      Spacingd : 
        keys : "img"
        pixdim : [1,1,5]

      Orientationd :
        keys : "img"
        axcodes : 'SPL'

      ScaleIntensityd :
        keys : "img"

      Resized :
        keys : "img"
        spatial_size : [48,256,256]
      EnsureTyped :
        keys : "img"

trainer :
  precision : 16
  max_epochs : 100
  gradient_clip_val : 10
