lighthining_model :
  name : "MRSClassficationImgOnly"
  parmas :

  model :
    name : "nnUnet"
    params :
      num_classes : 2
      plans_path : '/home/lab/inseo/brain/model_best.model.pkl'
      weight : '/home/lab/inseo/brain/model_best.model'
      
  optimizer :
    name : "AdamW"
    params : 
      lr : 0.0001
      weight_decay : 0.0005
  
  scheduler :
    name : "CosineAnnealingWarmUpRestarts"
    params : 
      T_0 : 50
      T_mult : 1
      eta_max : 0.001
      T_up : 10
      gamma : 0.5
    
datamodule :
  name : "BrainDataModule"
  params : 

  dataset :
    name : 'MRSImaOlnyDataset'
    params : 
      data_dir : "/home/lab/inseo/brain/data/total2"
  
  data_load_params :
    train_path : "/home/lab/inseo/brain/data/total2/train_mrs_3.csv"
    val_path : "/home/lab/inseo/brain/data/total2/val_mrs_3.csv"
    test_path : "/home/lab/inseo/brain/data/total2/test_mrs_3.csv"

  dataloader : 
    name :
    params :
      batch_size : 12
      num_workers : 7
      pin_memory : True

  transforms:
    train:
      LoadImaged : 
        keys : "img"
      AddChanneld :
        keys : "img"

      Spacingd : 
        keys : "img"
        pixdim : [1,1,5]

      Resized :
        keys : "img"
        spatial_size : [256,256,48]

      Orientationd :
        keys : "img"
        axcodes : 'RAS'

      ScaleIntensityd :
        keys : "img"

      RandRotated : 
        keys : "img"
        range_x : 0.2617993877991494

      EnsureTyped :
        keys : "img"

    val:
      LoadImaged : 
        keys : "img"

      AddChanneld :
        keys : "img"

      Spacingd : 
        keys : "img"
        pixdim : [1,1,5]

      Resized :
        keys : "img"
        spatial_size :  [256,256,48]

      Orientationd :
        keys : "img"
        axcodes : 'RAS'

      ScaleIntensityd :
        keys : "img"

      EnsureTyped :
        keys : "img"

trainer :
  precision : 16
  max_epochs : 50
  gradient_clip_val : 10
