lighthining_model :
  name : "MRSClassficationMultiModal1"
  parmas :

  model :
    name : "nnUnetMultiModalFeatureConcatTest4"
    params :
      num_classes : 2
      clinical_feature_len : 11
      head : mlp 
      plans_path : '/home/lab/inseo/brain/model_best.model.pkl'
      weight : '/home/lab/inseo/brain/nnunet-epoch=05-val_auc=0.705.ckpt'
    freeze_backbone : True

  optimizer :
    name : "AdamW"
    params : 
      lr : 0.001
      weight_decay : 0.0005
  
  scheduler :
    name : "CosineAnnealingWarmUpRestarts"
    params : 
      T_0 : 50
      T_mult : 1
      eta_max : 0.001
      T_up : 10
      gamma : 0.5

datamodule :
  name : "BrainDataModule"
  params : 

  dataset :
    name : 'MRSMultiDataset'
    params : 
      data_dir : "/home/lab/inseo/brain/data/total2"
  
  data_load_params :
    train_path : "/home/lab/inseo/brain/data/total2/train.csv"
    val_path : "/home/lab/inseo/brain/data/total2/val.csv"
    test_path : "/home/lab/inseo/brain/data/total2/test.csv"
    scaler_name : 'RobustScaler'
    categorical_cols : ['sex','toast']
    numerical_cols : ['age','bmi','ini_nih','hx_str','hx_htn','hx_smoke','hx_af','tx_throm','wbc','hb', 'plt', 'tc', 'tg', 'hdl', 'ldl', 'bun', 'cr', 'fbs', 'sbp', 'dbp']
    ignore_cols : ['image','label','mask']
    
  dataloader : 
    name :
    params :
      batch_size : 32
      num_workers : 7
      pin_memory : False

  transforms:
    train:
      LoadImaged : 
        keys : "img"
      AddChanneld :
        keys : "img"

      Spacingd : 
        keys : "img"
        pixdim : [1,1,1]

      Orientationd :
        keys : "img"
        axcodes : 'RSA'

      ScaleIntensityd :
        keys : "img"

      Resized :
        keys : "img"
        spatial_size : [96,96,96]

      RandRotated : 
        keys : "img"
        range_x : 0.2617993877991494

      EnsureTyped :
        keys : "img"

    val:
      LoadImaged : 
        keys : "img"

      AddChanneld :
        keys : "img"

      Spacingd : 
        keys : "img"
        pixdim : [1,1,1]

      Orientationd :
        keys : "img"
        axcodes : 'RSA'

      ScaleIntensityd :
        keys : "img"

      Resized :
        keys : "img"
        spatial_size : [96,96,96]
      EnsureTyped :
        keys : "img"
trainer :
  precision : 16
  max_epochs : 100
  gradient_clip_val : 10
